### PR TITLE
path_to_lines function

### PR DESCRIPTION
**Pull request by sgarciav**
Re-added the **path_to_lines** function int the ProtoConversions.cpp class to account for some gtri-uav-scrimmage plugins that make use of it.

### CODE REVIEW

**Comment by sgarciav** [comment]
Travis is failing to build with the following error:

```
[91m/usr/bin/ld: cannot find -lscrimmage-core
/usr/bin/ld: cannot find -lscrimmage-python
```

I have not seen this error when building on my machine.

**Comment by esquires** [comment]
Adding @crichardson332. Can you comment on the error?

**Comment by SyllogismRXS** [comment]
Sergio, once this travis build builds successfully (https://travis-ci.org/gtri/scrimmage/builds/392339844), try to resubmit your commit.

**Comment by crichardson332** [comment]
Looks like the scrimmage_ros project is failing to link to the new scrimmage-core and scrimmage-python targets that are now part of master. Has this been rebased onto master since merge commit 209200c?

**Comment by sgarciav** [comment]
Thanks guys!

**Pull request merged**
