### PR TITLE
add sleep() for pause efficiency

### PR DESCRIPTION
**Pull request by crichardson332**
- link to opencv libraries properly in exported target

### CODE REVIEW

**Comment by crichardson332** [comment]
This commit makes the simulator significantly more efficient in terms of cpu usage while paused.

**Comment by esquires** [comment]
This seems like it is going to sleep even when the simulation is not paused. Can we add an if statement so it is not slowed down when not paused?

**Comment by crichardson332** [comment]
Done.

**Comment by esquires** [comment]
Thanks!

**Pull request merged**
